---
title: "Functions included"
output: html_document
---

<br>

The **gapfraction** package implements a new barycentric interpolation spike-free canopy height model (CHM) algorithm based on Khosravipour et al. (2013)^[Khosravipour et al. (2013) Development of an algorithm to generate a LiDAR pit-free canopy height model. http://www.riegl.com/uploads/tx_pxpriegldownloads/khosravipour_SilviLaser2013.pdf] and (2016)^[Khosravipour et al. (2016) Generating spike-free digital surface models using LiDAR raw point clouds: A new approach for forestry applications. http://www.sciencedirect.com/science/article/pii/S0303243416300873], in addition to two new LiDAR metrics of canopy gap fraction ($P_o$), several individual tree crown (ITC) detection algorithms, canopy distance and direction metrics, effective leaf area index ($L_e$) and apparent clumping index ($ACI$) estimation methods. Four mathematical fisheye (hemispherical) lens models are implemented: equi-angular, equi-distant, stereographic, and orthographic. Finally, a new `radial.grid` function is included for polar plots, while a modified sun path plotting function is also provided. An alphabetical list of functions contained in the **gapfraction** package is provided below.

- `chm` - Simple canopy height model
- `chm.sf` - Barycentric interpolation spike-free canopy height model
- `dd.canopy` - Euclidean distance and direction to nearest canopy pixel from plot center
- `dd.crown` - Euclidean distance and direction to nearest tree crown from plot centers
- `itc.mw` - Variable-window individual tree crown detection
- `itc.mw.h` - Hierarchical variable-window individual tree crown detection
- `itc.wat` - Watershed segmentation individual tree crown detection
- `itc.wat.h` - Hierarchical watershed segmentation individual tree crown detection
- `Le.bl` - Ground-to-total-return ratio with a spherical leaf angle distribution
- `Le.n` - Contact frequency and vertical canopy cover-based effective LAI
- `radial.grid.hemi` - Modified radial.grid function supporting hemispherical lens geometries
- `P.hv` - Hemipsherical Voronoi canopy gap fraction
- `P.hv.par` - Parallel hemispherical Voronoi canopy gap fraction with SOCKS
- `P.pdn` - Point-density-normalized canopy gap fraction, effective LAI (Le), and ACI
- `sun.path` - Modified solar position plots of Thomas Steiner
- `vcc.aci` - Above-height cover index of vertical canopy cover
- `vcc.bl` - Beer-Lambert-Law-modified intensity-return ratio of vertical canopy cover
- `vcc.cv` - 2-D Cartesian Voronoi vertical canopy cover
- `vcc.fci` - First-echo cover index of vertical canopy cover
- `vcc.fr` - Canopy-to-first-return ration of vertical canopy cover
- `vcc.ir` - Intesity-return ratio of vertical canopy cover
- `vcc.p` - Canopy-to-total-pixel ratio of vertical canopy cover
- `vcc.r` - Canopy-to-total-return ratio of vertical canopy cover
- `vcc.sci` - Solberg's cover index of vertical canopy cover
